#!/bin/bash
# Use this script to compile your .cc files in dependency order.
# Assumes existence of syslibs.txt contains a list of any system
# libraries imported.

# Arguments:
#   $1 = name of file containing list of .cc files
#   $2 = name of the output file (defaults to a.out if not specified)
#   $3 = linker options e.g. "-lX11"

shopt -s nullglob globstar

cxx=g++

# - disable warnings about #pragma once in non-header files, since we have to import .cc files for IDE support
# - turn unhandled switch clauses into errors
cxxflags="-std=c++20 -fmodules-ts -Wall -g -Wno-pragma-once-outside-header -Werror=switch"
x11_link="-lX11"
if [ -d "/opt/X11/include" ]; then # MacOS
  cxxflags="$cxxflags -I /opt/X11/include"
  x11_link="-L /opt/X11/lib -lX11"
elif [ -d "/etc/X11" ]; then # Linux
  cxxflags="$cxxflags -I /etc/X11/include"
  x11_link="-L /etc/X11/lib -lX11"
fi
gcmsyspath="gcm.cache/**/*.gcm"

if [ $# -lt 1 ]; then
  echo "Usage:  $0 list-filename [output-name [linkage flags]]" 1>&2
  exit 1
fi

if [ -e "syslibs.txt" ]; then
  # shellcheck disable=SC2013,SC2086
  files=$(echo $gcmsyspath | tr ' ' '\n' | sed -E 's/.*\/(.*)\.gcm/\1/' | sort -u)
  for x in $(cat "syslibs.txt"); do
    if ! [[ $files =~ $x ]]; then
      echo $cxx $cxxflags -x c++-system-header -c $x
      $cxx $cxxflags -x c++-system-header -c $x
    fi
  done
fi

if [ $# -eq 2 ]; then
  name="-o $2"
  link="$x11_link"
elif [ $# -eq 3 ]; then
  name="-o $2"
  link="$x11_link $3"
fi

ok=1
for x in $(cat "$1"); do
  echo $cxx $cxxflags -c $x
  if ! $cxx $cxxflags -c $x; then
    ok=0
    break
  fi
done

if [ $ok -ne 0 ]; then
  echo $cxx ./*.o $name $link
  if ! $cxx ./*.o $name $link; then ok=0; fi
fi
rm ./*.o
exit $((1 - ok))
